Next step for testing ServalRPC.

diff --git a/auto-scenario b/auto-scenario
--- a/auto-scenario
+++ b/auto-scenario
@@ -1,47 +1,45 @@
 #! /bin/bash
 exec &> >(tee /tmp/.auto-scenario.log )
 
-#rpc_runloop_exception_handler () {
-#    echo -e "\e[37m\e[44m# Either an exception occured on the RPC runloop or the RPC server is not started at all!. See '$MINIWORLD_TRACEBACK_PATH' for runloop errors:\e[0m"
-#    cat $MINIWORLD_TRACEBACK_PATH
-#    echo -e "\e[37m\e[44m# --- ignoring for now!\e[0m"
-    #echo -e "\e[37m\e[44m# Fully aborting auto-scenario!\e[0m"
-    #pkill -TERM -P $$
-    #exit 1
-#}
+red=$'\e[1;37m\e[41m'
+grn=$'\e[1;37m\e[42m'
+blu=$'\e[1;37m\e[44m'
+end=$'\e[0m\e[0m'
+
+CORE_TOPO_PID=-1
 
 exec_scenario () {
-    echo -e "\e[30m\e[47m### Performing scenario: $@\e[0m"
+    printf "${grn}# Performing scenario: $@ \n${end}"
+    printf "\n\n${end}"
     (eval ./scenario $@)
     ret=$?
     if [ $ret -eq 0 ]; then
-        echo -e "\e[32m\e[47m### Scenario finished successfully!\e[0m"
+        printf "${grn}# Scenario finished successfully!\n${end}"
     else
-        echo -e "\e[31m\e[47m### Scenario failed with return code $ret...\n`./scenario | tail -n-6`\e[0m"
+        printf "${red}# Scenario failed with return code $ret...\n`./scenario | tail -n-6`\n${end}"
     fi
     return $ret
 }
 
 initialize_topology () {
-    echo -e "\e[30m\e[47m### Starting RPC scenario $1...\e[0m"
-    (cd /root/miniworld/MiniWorld && python miniworld/rpc/RPCStartScenario.py MiniWorld_Scenarios/serval_paper/$1)
-    init=$?
-    if [ $init -eq 0 ]; then
-        echo -e "\e[32m\e[47m### RPC scenario started successfully!\e[0m"
+    printf "${blu}# Starting RPC scenario $1...\n${end}"
+    python run_core_topology.py $1 &
+    CORE_TOPO_PID=$!
+    if [ $CORE_TOPO_PID -eq -1 ]; then
+        printf "${red}# Initialization failed.\n${end}"
     else
-        echo -e "\e[31m\e[47m### Initialization failed (returned $init).\e[0m"
+        printf "${blu}# Waiting...!\n${end}"
+        sleep 5
+        printf "${grn}# RPC scenario started successfully!\n${end}"
     fi
-    return $init
+    return $CORE_TOPO_PID
 }
 
 finalize_topology () {
-    echo -e "\e[30m\e[47m### Iteration done, finalizing topology.\e[0m"
-    pkill -fe RPCServer.py > /dev/null
-    ./miniworld_event_hook_cleanup.sh
-    #(cd /root/miniworld/MiniWorld && python miniworld/rpc/RPCStopScenario.py)
-    #return $?
+    printf "${grn}# Iteration done, finalizing topology (PID: $CORE_TOPO_PID).\n${end}"
+    kill -n 2 $CORE_TOPO_PID
 }
-trap 'echo "Stopping"' SIGINT
+trap finalize_topology SIGINT
 
 beautify_params () {
     for param in "$@"; do
@@ -53,17 +51,16 @@ beautify_params () {
 mapfile -t LINES <$1
 
 AUTO_SCENARIO_START=`date +%Y-%m-%d_%H-%M`
-AUTO_LOGFOLDER=/tmp/serval-monitor/${AUTO_SCENARIO_START}_$(basename ${1})
-MINIWORLD_TRACEBACK_PATH=$AUTO_LOGFOLDER/miniworld_traceback.log
+AUTO_LOGFOLDER="/tmp/serval-monitor/${AUTO_SCENARIO_START}_$(basename ${1})"
 
 trap rpc_runloop_exception_handler SIGUSR1
 MAIN_PROCESS_PID=$$
 
-echo -e "\e[37m\e[44m# Autorunning scenario configurations from $1, pid: $MAIN_PROCESS_PID\e[0m"
+printf "${blu}# Autorunning scenario configurations from $1, pid: $MAIN_PROCESS_PID\n${end}"
 
 for line in "${LINES[@]}"; do
-    if [[ $line == \#* ]]; then 
-	echo -e "\n\e[37m\e[40m## Skipping set: $line\e[0m"
+    if [[ $line == \#* ]]; then
+	printf "${blu}# Skipping set: $line\n${end}"
 	continue
     fi
 
@@ -76,28 +73,31 @@ for line in "${LINES[@]}"; do
     params=${line_arr[@]:2:$(( len-4 ))}
     repeat=${line_arr[-2]:1:${#line_arr[-2]}}
     topology=${line_arr[-1]}
-    
-    echo -e "\n\e[37m\e[40m## Running set:   $env | $topology | $scenario | repeating $repeat times\e[0m"
+
+    printf "${blu}# Running set:   $env | $topology | $scenario | repeating $repeat times\n${end}"
 
     run=1
     while [ $run -le $repeat ]; do
-        echo -e "\e[30m\e[47m### Iteration #$run: $env | $topology | $scenario\e[0m"
+        printf "${blu}# Iteration #$run: $env | $topology | $scenario\n${end}"
         scenarioname=${line_arr[1]}
         SCENARIO_LOGFOLDER=$AUTO_LOGFOLDER/$scenarioname-$env
-        
+
         RUN_START=`date +%Y-%m-%d_%H-%M`
         SHORT_PARAMS=`eval beautify_params $params`
-        
-        export LOGFOLDER=$SCENARIO_LOGFOLDER/$topology-$scenarioname-$SHORT_PARAMS-run_`printf "%03g" $run`--$RUN_START
+
+        export LOGFOLDER="$SCENARIO_LOGFOLDER/$topology-$scenarioname-$SHORT_PARAMS-run_`printf "%03g" $run`--$RUN_START"
         mkdir -p $LOGFOLDER
         echo "$line" > $LOGFOLDER/parameters.conf
-        
+
+        initialize_topology $topology
         exec_scenario $env $scenario --logfolder $LOGFOLDER |& tee $LOGFOLDER/scenario.log 2>&1
-        
+
+        finalize_topology
+
+        mkdir -p $LOGFOLDER/netmon; mv /tmp/netmon* $_
+
         run=$(( run + 1 ))
     done
 done
 
-kill $WATCHER_PID > /dev/null
-
-echo -e "\n\e[37m\e[44m# Done autorunning scenario configurations from $1\e[0m"
+printf "${grn}# Done autorunning scenario configurations from $1\n${end}"
diff --git a/scenario b/scenario
--- a/scenario
+++ b/scenario
@@ -1,20 +1,26 @@
 #! /bin/bash
+
+red=$'\e[1;31m'
+grn=$'\e[1;32m'
+blu=$'\e[1;34m'
+end=$'\e[0m'
+
 if [ "$1" = "-h" ] || [ "$#" -lt 2 ]; then
-    echo "usage: $0 (core | help) scenario p w i [0 ... | -a ] [--logfolder <path>]"
-    echo "starts a scenario with prepare/initiate at all given nodes"
-    echo "       params for scripts: p - preparations"
-    echo "       params for scripts: w - watch-agents"
-    echo "       params for scripts: i - initiate"
-    echo
-    echo "With help, a help text for the scenario will be printed."
-    echo
-    echo "Return codes:"
-    echo "    1: generic error"
-    echo "    2: scenario nonexistant"
-    echo "    3: no nodes found"
-    echo "    4: simulation type not supported"
-    echo "    10-19: error in Phase 0-9"
-    echo "    130: script killed by ctrl-c"
+    printf "${red}usage: $0 (core | help) scenario p w i [0 ... | -a ] [--logfolder <path>]\n${end}"
+    printf "${red}starts a scenario with prepare/initiate at all given nodes\n${end}"
+    printf "${red}       params for scripts: p - preparations\n${end}"
+    printf "${red}       params for scripts: w - watch-agents\n${end}"
+    printf "${red}       params for scripts: i - initiate\n${end}"
+    printf "\n"
+    printf "${red}With help, a help text for the scenario will be printed.\n${end}"
+    printf "\n"
+    printf "${red}Return codes:\n${end}"
+    printf "${red}    1: generic error\n${end}"
+    printf "${red}    2: scenario nonexistant\n${end}"
+    printf "${red}    3: no nodes found\n${end}"
+    printf "${red}    4: simulation type not supported\n${end}"
+    printf "${red}    10-19: error in Phase 0-9\n${end}"
+    printf "${red}    130: script killed by ctrl-c\n${end}"
     exit
 fi
 
@@ -32,16 +38,16 @@ INIT_ARGS=$5
 
 ###Build active nodes array and check if appendix argument is present
 VARARGS=(${@:6})
-for i in "${!VARARGS[@]}"; do 
+for i in "${!VARARGS[@]}"; do
     if [ "${VARARGS[$i]}" = "--logfolder" ]; then
         LOCAL_LOG_FOLDER="${VARARGS[$((i+1))]}"
         break
     fi
-    
-    ACTIVE_NODES="$ACTIVE_NODES ${VARARGS[$(( $i - 1 ))]}"
+
+    ACTIVE_NODES="$ACTIVE_NODES ${VARARGS[$(( $i - 3 ))]}"
 done
 
-LOG_FOLDER=/tmp/serval-monitor
+LOG_FOLDER="/tmp/serval-monitor_tmp"
 if [ -z ${LOCAL_LOG_FOLDER+x} ]; then LOCAL_LOG_FOLDER=$LOG_FOLDER-$SCENARIO-`date +%Y-%m-%d_%H-%M`; fi
 mkdir -p $LOCAL_LOG_FOLDER
 
@@ -54,24 +60,24 @@ rm -f $SEVERAL_ALL_SIDS_FILE
 
 # test if scenario is available
 if [ ! -d "$SCENARIO" ]; then
-    echo -e "\e[1;31mError: Scenario $SCENARIO does not exist\e[0m"
+    printf "${red}Error: Scenario $SCENARIO does not exist\n${end}"
     exit 2
 fi
-echo -e "\e[1;32mRunning Scenario $SCENARIO "
+printf "${grn}## Running Scenario $SCENARIO\n"
 
 NODES=()
 if [ "$TYPE" == "core" ]; then
     while read N; do NODES=( "${NODES[@]}" "$N" ); done < <(find /tmp/ 2>/dev/null | grep pycore.*/n[0-9]*$ | sort)
-    
+
     NODE_CNT=`find /tmp/ 2>/dev/null | grep pycore.*/n[0-9]*$ | wc -l`
     if [ "$NODE_CNT" == "0" ]; then
-        echo -e "\e[1;31mError: Couldn't find any core nodes\e[0m"
+        printf "${red}Error: Couldn't find any core nodes\n${end}"
         exit 3
     fi
 
-    echo -n -e "  Using CORE Nodes "
-    for NODE in ${NODES[@]}; do printf "`basename $NODE` "; done; echo
-    
+    printf "## Using Nodes "
+    for NODE in ${NODES[@]}; do printf "`basename $NODE` "; done;
+
     exec_par () {
         PIDS=""
         FAIL="0"
@@ -81,25 +87,22 @@ if [ "$TYPE" == "core" ]; then
         done
         for PID in $PIDS; do
             wait $PID || let "FAIL=$?"
-            printf .
-            if [ "$FAIL" != "0" ]; then echo -e "\e[1;31mPID $PID failed with $FAIL, aborting scenario.\e[0m"; exit 1; fi
+            if [ "$FAIL" != "0" ]; then printf "${red}PID $PID failed with $FAIL, aborting scenario.\n${end}"; exit 1; fi
         done
-        echo
     }
-    
+
     exec_seq () {
-        echo
         for N in $1; do
             vcmd -c ${NODES[$(( $N - 1 ))]} -- sh -c "${@:2}"
-            echo
+            printf "\n"
         done
     }
-    
+
     exec () { vcmd -c ${NODES[$(($1-1))]} -- sh -c "${@:2}"; }
     shell () { vcmd -c ${NODES[$(($1-1))]} -- sh; }
-    
+
 else
-    echo -e "\e[1;31mError: Type $TYPE is not supported\e[0m"
+    printf "${red}Error: Type $TYPE is not supported\n${end}"
     exit 4
 fi
 
@@ -109,54 +112,40 @@ ALL_NODES=`seq -s " " 1 $NODE_CNT`
 # replacing -a option for all nodes
 if [ "$ACTIVE_NODES" = " -a" ]; then ACTIVE_NODES="$ALL_NODES"; fi
 ACTIVE_NODE_CNT=`echo $ACTIVE_NODES | wc -w`
-echo -n -e "  Active: ${ACTIVE_NODES[@]}"
-echo -e "\e[0m\n"
+printf "\n${grn}## Active: ${ACTIVE_NODES[@]}\n${end}"
 
 
 ### PHASE 1
 export PHASE=11
-echo -n -e "\e[1;34mPhase 1 - Prepare: $SCENARIO_FOLDER/prepare $NODE_CNT $ACTIVE_NODE_CNT $PREP_ARGS\e[0m"
+printf "${blu}## Phase 1 - Prepare: $SCENARIO_FOLDER/prepare $NODE_CNT $ACTIVE_NODE_CNT $PREP_ARGS\n${end}"
 echo "`date_ms`, 1, prepare" >> $TIMING_FILE
 exec_seq "$ACTIVE_NODES" "$SCENARIO_FOLDER/prepare $NODE_CNT $ACTIVE_NODE_CNT $PREP_ARGS"
 
 ### PHASE 2
 export PHASE=12
 echo "`date_ms`, 2, system-monitoring" >> $TIMING_FILE
-
-echo -n -e "\e[1;34m        - Starting system monitoring\e[0m"
+printf "${blu}## Phase 2 - Starting system monitoring\n${end}"
 exec_par "$ALL_NODES" "/serval-tests/monitor system"
 
 ## PHASE 3
 export PHASE=13
-echo -n -e "\e[1;34mPhase 3 - Generating SIDs and starting servald\e[0m"
+printf "${blu}## Phase 3 - Generating SIDs and starting servald\n${end}"
 echo "`date_ms`, 3, servald-start" >> $TIMING_FILE
 exec_par "$ALL_NODES" 'export HOST=`hostname | cut -d u -f2 | sed -e "s/^0*//g"`; servald keyring add "" `printf "%2x" $((16+$HOST))` > /dev/null; servald start > /dev/null; sleep 2'
 
 ## PHASE 3.1
-echo -n -e "\e[1;34m        - Collecting serval sids\e[0m"
-exec_seq "$ALL_NODES" "servald id self | tail -n1" | awk '{print $3}' | grep -v '^$' >> $SEVERAL_ALL_SIDS_FILE
-echo
-
-echo -n -e "\e[1;34m        - Distributing serval sids\e[0m"
-
-### PHASE 3.2
-#if [ "$TYPE" == "core" ]; then
-#    echo -n -e "\e[1;34m        - Initiating scan for other servald instances\e[0m"
-#    exec_seq "$ALL_NODES" 'for i in `ifconfig | grep "inet addr" | grep -v "127.0.0" | cut -d":" -f 2 | cut -d"." -f1,2,3`; do echo -n "$i.255: "; servald scan $i.255; done; exit 0'
-#elif [ "$TYPE" == "miniworld" ]; then
-#    echo -n -e "\e[1;34m        - Initiating scan for other servald instances\e[0m"
-#    exec_seq "$ALL_NODES" 'for i in `ifconfig | grep -A2 "eth" | grep "Bcast" | cut -d":" -f 2 | cut -d" " -f 1`; do echo -n "$i: "; servald scan $i; done; exit 0'
-#fi
+printf "${blu}## Phase 3 - Collecting serval sids\n${end}"
+exec_seq "$ALL_NODES" "servald id self" | grep -v "sid" | grep -v "^1$" | grep -v "^$" >> $SEVERAL_ALL_SIDS_FILE
 
 ### PHASE 4
 export PHASE=14
-echo -n -e "\e[1;34mPhase 4 - Starting servald monitoring\e[0m"
+printf "${blu}## Phase 4 - Starting servald monitoring\n${end}"
 echo "`date_ms`, 4, servald-monitoring" >> $TIMING_FILE
 exec_par "$ALL_NODES" "/serval-tests/monitor serval"
 
 ### PHASE 5
 export PHASE=15
-echo -n -e "\e[1;34mPhase 5 - Starting watch-agents: $SCENARIO_FOLDER/watch-agent $NODE_CNT $ACTIVE_NODE_CNT $WATCH_ARGS\e[0m"
+printf "${blu}## Phase 5 - Starting watch-agents: $SCENARIO_FOLDER/watch-agent $NODE_CNT $ACTIVE_NODE_CNT $WATCH_ARGS\n${end}"
 echo "`date_ms`, 5, watch-agent-start" >> $TIMING_FILE
 
 # using trap to kill running vcmds
@@ -165,43 +154,41 @@ trap "kill $AGENTS 2> /dev/null; echo Killed agents; exit 130" SIGINT SIGTERM
 for NODE in $ALL_NODES; do
     exec $NODE "$SCENARIO_FOLDER/watch-agent $NODE_CNT $ACTIVE_NODE_CNT $WATCH_ARGS" &
     AGENTS="$AGENTS $!"
-    printf .
 done
-echo
 
 ### PHASE 6
 export PHASE=16
-echo -n -e "\e[1;34mPhase 6 - Initiating Scenario: $SCENARIO_FOLDER/initiate $NODE_CNT $ACTIVE_NODE_CNT $INIT_ARGS\e[0m"
+printf "${blu}## Phase 6 - Initiating Scenario: $SCENARIO_FOLDER/initiate $NODE_CNT $ACTIVE_NODE_CNT $INIT_ARGS\n${end}"
 echo "`date_ms`, 6, initiate" >> $TIMING_FILE
 exec_seq "$ACTIVE_NODES" "$SCENARIO_FOLDER/initiate $NODE_CNT $ACTIVE_NODE_CNT $INIT_ARGS"
 
 ### PHASE 7
 export PHASE=17
-echo -e "\e[1;34mPhase 7 - Waiting for agents:\e[0m"
+printf "${blu}## Phase 7 - Waiting for agents:\n${end}"
 echo "`date_ms`, 7, watch-agent-wait" >> $TIMING_FILE
 for PID in $AGENTS; do
-    wait $PID || echo "  Watch-Agent $PID failed ($?)."
+    wait $PID || printf "${red}  Watch-Agent $PID failed ($?).\n${end}"
 done
 echo
 
 if [ "$FAIL" == "0" ]; then
-    echo -n -e "\e[1;32mPhase 7 - watch-agents finished, sleeping 5 seconds to have a trailer in monitoring\e[0m"
-    for i in {1..5}; do printf .; sleep 1; done
-    echo
+    printf "${grn}## Phase 7 - watch-agents finished, sleeping 5 seconds to have a trailer in monitoring"
+    for i in {1..5}; do printf "."; sleep 1; done; printf "\n${end}"
 fi
 
 ### PHASE 8
 export PHASE=18
-echo -n -e "\e[1;34mPhase 8 - Stopping monitoring\e[0m"
+printf "${blu}## Phase 8 - Stopping monitoring\n${end}"
 echo "`date_ms`, 8, stop-monitoring" >> $TIMING_FILE
 exec_par "$ALL_NODES" "/serval-tests/monitor stop; servald stop > /dev/null"
 
 ### PHASE 9
 export PHASE=19
-echo -n -e "\e[1;34mPhase 9 - Data Collection: \e[0m"
+printf "${blu}## Phase 9 - Data Collection:\n${end}"
 echo "`date_ms`, 9, data-collection" >> $TIMING_FILE
-mv $LOG_FOLDER/*/* $LOCAL_LOG_FOLDER
 
-echo
-echo -e "\e[1;32mScenario $SCENARIO done.\e[0m"
+mv $LOG_FOLDER/*/* $LOCAL_LOG_FOLDER
+rm -rf $LOG_FOLDER
+
+printf "${grn}## Scenario $SCENARIO done.\n${end}"
 echo "`date_ms`, 10, finished" >> $TIMING_FILE
